# Unit 2 – Iris Dataset
Neural Network Forward Pass with Manual and Code-Based Computation

In [47]:
import numpy as np

## Input and Target Output

In [48]:
X = np.array([5.1, 3.5, 1.4, 0.2])
target = np.array([0.7, 0.2, 0.1])

## Dense Layer Class

In [49]:
class Dense_Layer:
    def __init__(self, weights, bias, activation):
        self.weights = np.array(weights, dtype=float)
        self.bias = np.array(bias, dtype=float)
        self.activation = activation

    def weighted_sum(self, inputs):
        return np.dot(inputs, self.weights) + self.bias

    def activate(self, z):
        if self.activation == "relu":
            return np.maximum(0, z)
        elif self.activation == "sigmoid":
            return 1 / (1 + np.exp(-z))
        elif self.activation == "softmax":
            e = np.exp(z - np.max(z))
            return e / np.sum(e)
        else:
            raise ValueError("Unsupported activation")

    def forward(self, inputs):
        z = self.weighted_sum(inputs)
        return self.activate(z)

    def categorical_cross_entropy_loss(self, predicted, target):
        predicted = np.clip(predicted, 1e-15, 1 - 1e-15)
        return -np.sum(target * np.log(predicted))

## Weights and Biases

In [50]:
W1 = [
    [0.2,  0.5, -0.3],
    [0.1, -0.2,  0.4],
    [-0.4, 0.3,  0.2],
    [0.6, -0.1,  0.5]
]
B1 = [3.0, -2.1, 0.6]

W2 = [
    [0.3, -0.5],
    [0.7,  0.2],
    [-0.6, 0.4]
]
B2 = [4.3, 6.4]

W3 = [
    [0.5, -0.3, 0.8],
    [-0.2, 0.6, -0.4]
]
B3 = [-1.5, 2.1, -3.3]

## Forward Pass – Hidden Layer 1 (ReLU)

In [51]:
layer1 = Dense_Layer(W1, B1, "relu")
A1 = layer1.forward(X)
A1

array([3.93, 0.15, 0.85])

## Forward Pass – Hidden Layer 2 (Sigmoid)

In [52]:
layer2 = Dense_Layer(W2, B2, "sigmoid")
A2 = layer2.forward(A1)
A2

array([0.99378157, 0.99187781])

## Output Layer (Softmax)

In [53]:
layer3 = Dense_Layer(W3, B3, "softmax")
output = layer3.forward(A2)
output

array([0.0265075 , 0.96865119, 0.00484132])

## Loss Calculation (Categorical Cross-Entropy)

In [54]:
loss = layer3.categorical_cross_entropy_loss(output, target)
loss

np.float64(3.080656405230887)

## Final Result

- Predicted Class: **Iris-versicolor**
- Loss Value Computed Successfully