INSTALL THE FOLLOWING PYTHON PACKAGES FIRST BEFORE RUNNING THE PROGRAM

1) Numpy
2) NNFS - for the Spiral dataset
3) scikit-learn - for the iris dataset

In [15]:
# Library imports
import numpy as np

Create classes for modularity

In [16]:
# Hidden Layers
# Dense
class Layer_Dense:
    # Layer initialization
    # randomly initialize weights and set biases to zero
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))


    # Forward pass
    def forward(self, inputs):
        # Remember the input values
        self.inputs = inputs
        # Calculate the output values from inputs, weight and biases
        self.output = np.dot(inputs, self.weights) + self.biases

    # Backward pass/Backpropagation
    def backward(self, dvalues):
        # Gradients on parameters:
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
        # Gradient on values
        self.dinputs = np.dot(dvalues, self.weights.T)


In [17]:
# Activation Functions
# Included here are the functions for both the forward and backward pass

# Linear
class ActivationLinear:
    def forward(self, inputs):
        self.inputs = inputs
        self.output = inputs

    def backward(self, dvalues):
        self.dinputs = dvalues.copy()

# Sigmoid
class ActivationSigmoid:
    def forward(self, inputs):
        self.inputs = inputs
        self.output = 1 / (1 + np.exp(-inputs))

    def backward(self, dvalues):
        self.dinputs = dvalues * (self.output * (1 - self.output))

# TanH
class ActivationTanH:
    def forward(self, inputs):
        self.inputs = inputs
        self.output = np.tanh(inputs)

    def backward(self, dvalues):
        self.dinputs = dvalues * (1 - self.output ** 2)

# ReLU
class Activation_ReLU:
    # Forward pass
    def forward(self, inputs):
        # Remember the input values
        self.inputs = inputs
        # Calculate the output values from inputs
        self.output = np.maximum(0, inputs)

    # Backward pass
    def backward(self, dvalues):
        # Make a copy of the original values first
        self.dinputs = dvalues.copy()
    
        # Zero gradient where input values were negative
        self.dinputs[self.inputs <= 0] = 0

# Softmax
class Activation_Softmax:
    # Forward pass
    def forward(self, inputs):
        # Remember the inputs values
        self.inputs = inputs

        # Get the unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

    # Backward pass
    def backward(self, dvalues):
        # Create uninitialized array
        self.dinputs = np.empty_like(dvalues)

        # Enumerate outputs and gradients
        for index, (single_output, single_dvalues) in enumerate(zip(self.output, dvalues)):

            # Flatten output array
            single_output = single_output.reshape(-1, 1)
            # Calculate Jacobian matrix of the output
            jacobian_matrix = np.diagflat(single_output) - np.dot(single_output, single_output.T)
            # Calculate the sample-wise gradient
            # and add it to the array of sample gradients
            self.dinputs[index] = np.dot(jacobian_matrix, single_dvalues)

In [18]:
# Loss functions

class Loss:
    # Calculate the data and regularization losses
    # Given the model output and grou truth/target values
    def calculate(self, output, y):
        # Calculate sample losses
        sample_losses = self.forward(output, y)
        # Calculate the mean loss
        data_loss = np.mean(sample_losses)
        # Return the mean loss
        return data_loss

# MSE
class Loss_MSE:
    def forward(self, y_pred, y_true):
        # Calculate Mean Squared Error
        return np.mean((y_true - y_pred) ** 2, axis=-1)

    def backward(self, y_pred, y_true):
        # Gradient of MSE loss
        samples = y_true.shape[0]
        outputs = y_true.shape[1]
        self.dinputs = -2 * (y_true - y_pred) / outputs
        # Normalize gradients over samples
        self.dinputs = self.dinputs / samples

# Binary Cross-Entropy
class Loss_BinaryCrossEntropy:
    def forward(self, y_pred, y_true):
        # Clip predictions
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        # Calculate Binary Cross Entropy
        return -(y_true * np.log(y_pred_clipped) + (1 - y_true) * np.log(1 - y_pred_clipped))

    def backward(self, y_pred, y_true):
        # Gradient of BCE loss
        samples = y_true.shape[0]
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        self.dinputs = - (y_true / y_pred_clipped - (1 - y_true) / (1 - y_pred_clipped))
        # Normalize gradients over samples
        self.dinputs = self.dinputs / samples

# Categorical Cross-Entropy
class Loss_CategoricalCrossEntropy(Loss):
    # Forward pass
    def forward(self, y_pred, y_true):
        # Number of samples in a batch
        samples = y_pred.shape[0]

        # Clip data to prevent division by 0
        # Clip both sides to not drag mean towards any value
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        # Probabilities for target values
        # Only if categorical labels
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        # Mask values - only for one-hot encoded labels
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)

        # Losses
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

    # Backward pass
    def backward(self, dvalues, y_true):
        # Number of samples
        samples = len(dvalues)
        # Number of labels in every sample
        # Use the first sample to count them
        labels = len(dvalues[0])

        # Check if labels are sparse, turn them into one-hot vector values
        # the eye function creates a 2D array with ones on the diagonal and zeros elsewhere
        if len(y_true.shape) == 1:
            y_true = np.eye(labels)[y_true]

        # Calculate the gradient
        self.dinputs = -y_true / dvalues
        self.dinputs = self.dinputs / samples


<!-- Star -->

In [19]:
# Start of Optimizers

class Optimizer:
    # Accept learning rate, decay, momentum, and adaptive (Adagrad) options
    def __init__(self, learning_rate=1.0, decay=0.0, momentum=0.0, adaptive=False, epsilon=1e-7):
        self.learning_rate = learning_rate
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.iterations = 0
        self.momentum = momentum
        self.adaptive = adaptive
        self.epsilon = epsilon

    def pre_update_params(self):
        # Apply learning rate decay if set using Inverse Time Decay formula
        if self.decay:
            self.current_learning_rate = self.learning_rate / (1 + self.decay * self.iterations)

    def update_params(self, layer):
        # If momentum is used, initialize momentum arrays if not present
        if self.momentum:
            if not hasattr(layer, 'weight_momentums'):
                layer.weight_momentums = np.zeros_like(layer.weights)
                layer.bias_momentums = np.zeros_like(layer.biases)
        # If adaptive (Adagrad) is used, initialize cache arrays if not present
        if self.adaptive:
            if not hasattr(layer, 'weight_cache'):
                layer.weight_cache = np.zeros_like(layer.weights)
                layer.bias_cache = np.zeros_like(layer.biases)

        # Vanilla SGD
        if self.momentum and not self.adaptive:
            # Update with momentum
            layer.weight_momentums = self.momentum * layer.weight_momentums - self.current_learning_rate * layer.dweights
            layer.bias_momentums = self.momentum * layer.bias_momentums - self.current_learning_rate * layer.dbiases
            layer.weights += layer.weight_momentums
            layer.biases += layer.bias_momentums
        elif self.adaptive:
            # Adagrad update
            layer.weight_cache += layer.dweights ** 2
            layer.bias_cache += layer.dbiases ** 2
            layer.weights += -self.current_learning_rate * layer.dweights / (np.sqrt(layer.weight_cache) + self.epsilon)
            layer.biases += -self.current_learning_rate * layer.dbiases / (np.sqrt(layer.bias_cache) + self.epsilon)
        else:
            # Standard SGD
            layer.weights += -self.current_learning_rate * layer.dweights
            layer.biases += -self.current_learning_rate * layer.dbiases

    def post_update_params(self):
        self.iterations += 1

Use most of the classes to create a functioning neural network, capable of performing a forward and backward pass

We can use a sample dataset from the Spiral module.  

We can also use the IRIS dataset.

In [20]:
# Spiral Data
import nnfs
from nnfs.datasets import spiral_data

# Create the dataset
X, y = spiral_data(samples = 100, classes = 3)

# print(X[:5])
# print(X.shape)
# print(y[:5])
# print(y.shape)

In [21]:
# Iris Dataset
# From the scikit-learn library
# from sklearn.datasets import load_iris
# iris = load_iris()
# X = iris.data # Features
# y = iris.target # Target labels

# print(X[:5])
# print(X.shape)
# print(y[:5])
# print(y.shape)

In [22]:
# Neural Network initialization
# Create a Dense Layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Make sure you check the shape of the features, in order to adjust the input size of the first layer
# dense1 = Layer_Dense(4, 3)

# Create a ReLU activation for the first Dense layer
activation1 = Activation_ReLU()

# Create a 2nd dense layer with 3 input and 3 output values
dense2 = Layer_Dense(3, 3)

# Create a Softmax activation for the 2nd Dense layer
activation2 = Activation_Softmax()

# Create a loss function
loss_function = Loss_CategoricalCrossEntropy()

# Create the optimizer
optimizer = Optimizer()

PERFORM ONLY 1 PASS

In [23]:
# Perform a forward pass of our training data
# give the input from the dataset to the first layer
dense1.forward(X)

# Activation function
activation1.forward(dense1.output)

# Pass on the 2nd layer
dense2.forward(activation1.output)

activation2.forward(dense2.output)

# Calculate the loss
loss_function.forward(activation2.output, y)

# Check the model's performance
predictions = np.argmax(activation2.output, axis=1)
if len(y.shape) == 2:
    y = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)

# Print the accuracy
print('acc:', accuracy)

acc: 0.3466666666666667


In [24]:
# Perform a backward pass of our training data
# From loss to 2nd softmax activation
loss_function.backward(activation2.output, y)
dvalues = loss_function.dinputs # Gradient of the loss w.r.t softmax output

print(dvalues.shape)
# print(dvalues)

# From 2nd softmax to 2nd dense layer
activation2.backward(dvalues)
# From 2nd dense layer to 1st ReLU activation
dense2.backward(activation2.dinputs)

# From 1st ReLU activation to 1st dense layer
activation1.backward(dense2.dinputs)
dense1.backward(activation1.dinputs)

(300, 3)


In [25]:
# Check the gradient values of the weights and biases of the established layers
print(dense1.dweights)
print(dense1.dbiases)
print(dense2.dweights)
print(dense2.dbiases)


# Update the weights and biases
optimizer.update_params(dense1)
optimizer.update_params(dense2)

[[ 1.61555004e-04  8.31184774e-05  9.34864333e-05]
 [ 3.88017969e-04 -3.81259163e-04  1.46209627e-04]]
[[-0.00122047  0.00023749  0.00027322]]
[[-4.36244985e-05  2.04992295e-04 -1.61367796e-04]
 [-3.42447144e-05 -2.61607194e-05  6.04054337e-05]
 [ 1.46996461e-05 -1.32031281e-04  1.17331635e-04]]
[[-5.90082766e-06 -7.59300306e-06  1.34938307e-05]]


In [26]:
# Training loop for 1000 epochs
epochs = 1000
for epoch in range(epochs):
    # Forward pass
    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    # Loss calculation
    loss = loss_function.calculate(activation2.output, y)

    # Accuracy calculation
    predictions = np.argmax(activation2.output, axis=1)
    y_true = y
    if len(y_true.shape) == 2:
        y_true = np.argmax(y_true, axis=1)
    accuracy = np.mean(predictions == y_true)

    # Backward pass
    loss_function.backward(activation2.output, y)
    activation2.backward(loss_function.dinputs)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    # Update weights and biases
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)

    # Print loss and accuracy every 100 epochs
    if (epoch+1) % 100 == 0:
        print(f"Epoch {epoch+1}: loss={loss:.4f}, acc={accuracy:.4f}")

Epoch 100: loss=1.0914, acc=0.4267
Epoch 200: loss=1.0706, acc=0.4467
Epoch 300: loss=1.0625, acc=0.4367
Epoch 400: loss=1.0608, acc=0.4300
Epoch 500: loss=1.0604, acc=0.4267
Epoch 600: loss=1.0602, acc=0.4267
Epoch 700: loss=1.0602, acc=0.4200
Epoch 800: loss=1.0602, acc=0.4167
Epoch 900: loss=1.0601, acc=0.4167
Epoch 1000: loss=1.0601, acc=0.4200


## Optimizer Comparison

We will compare two optimizers:

1. SGD with momentum
2. Adagrad (adaptive gradient)

We will observe:
- How many epochs it takes for the loss to stabilize
- The final accuracy of the model

In [27]:
# SGD with momentum
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()
loss_function = Loss_CategoricalCrossEntropy()
optimizer_sgd = Optimizer(learning_rate=1.0, momentum=0.9)

losses_sgd = []
accuracies_sgd = []
for epoch in range(1000):
    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)
    loss = loss_function.calculate(activation2.output, y)
    predictions = np.argmax(activation2.output, axis=1)
    y_true = y
    if len(y_true.shape) == 2:
        y_true = np.argmax(y_true, axis=1)
    accuracy = np.mean(predictions == y_true)
    losses_sgd.append(loss)
    accuracies_sgd.append(accuracy)
    loss_function.backward(activation2.output, y)
    activation2.backward(loss_function.dinputs)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)
    optimizer_sgd.update_params(dense1)
    optimizer_sgd.update_params(dense2)

In [28]:
# Adagrad
dense1_adagrad = Layer_Dense(2, 3)
activation1_adagrad = Activation_ReLU()
dense2_adagrad = Layer_Dense(3, 3)
activation2_adagrad = Activation_Softmax()
loss_function_adagrad = Loss_CategoricalCrossEntropy()
optimizer_adagrad = Optimizer(learning_rate=1.0, adaptive=True)

losses_adagrad = []
accuracies_adagrad = []
for epoch in range(1000):
    dense1_adagrad.forward(X)
    activation1_adagrad.forward(dense1_adagrad.output)
    dense2_adagrad.forward(activation1_adagrad.output)
    activation2_adagrad.forward(dense2_adagrad.output)
    loss = loss_function_adagrad.calculate(activation2_adagrad.output, y)
    predictions = np.argmax(activation2_adagrad.output, axis=1)
    y_true = y
    if len(y_true.shape) == 2:
        y_true = np.argmax(y_true, axis=1)
    accuracy = np.mean(predictions == y_true)
    losses_adagrad.append(loss)
    accuracies_adagrad.append(accuracy)
    loss_function_adagrad.backward(activation2_adagrad.output, y)
    activation2_adagrad.backward(loss_function_adagrad.dinputs)
    dense2_adagrad.backward(activation2_adagrad.dinputs)
    activation1_adagrad.backward(dense2_adagrad.dinputs)
    dense1_adagrad.backward(activation1_adagrad.dinputs)
    optimizer_adagrad.update_params(dense1_adagrad)
    optimizer_adagrad.update_params(dense2_adagrad)

In [29]:
# Find epoch where loss stabilizes (change < 1e-4 for 10 epochs)
def find_stable_epoch(losses):
    for i in range(10, len(losses)):
        if max(abs(np.diff(losses[i-10:i]))) < 1e-4:
            return i
    return len(losses)

stable_epoch_sgd = find_stable_epoch(losses_sgd)
stable_epoch_adagrad = find_stable_epoch(losses_adagrad)

print(f"SGD with momentum: stabilized at epoch {stable_epoch_sgd}, final accuracy: {accuracies_sgd[-1]:.4f}")
print(f"Adagrad: stabilized at epoch {stable_epoch_adagrad}, final accuracy: {accuracies_adagrad[-1]:.4f}")

SGD with momentum: stabilized at epoch 10, final accuracy: 0.4267
Adagrad: stabilized at epoch 48, final accuracy: 0.4433
